name: sitronix
services:
  postgres:
    container_name: sitronix_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sitronix'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=sitronix'
    ports:
      - '5434:5432'  # Notez que le port interne de PostgreSQL est 5432
volumes:
  postgres_data:
    driver: local